CREATE TABLE PUBLIC.DEVICE
(
  ID BIGINT NOT NULL,
  SERIAL_NUMBER CHARACTER VARYING(255),
  WAREHOUSE_ID BIGINT,
  CONSTRAINT PK_DEVICE PRIMARY KEY (ID),
  CONSTRAINT FK_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID)
      REFERENCES WAREHOUSE (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
