CREATE TABLE COMPANY
(
  ID BIGINT NOT NULL,
  NAME CHARACTER VARYING(255) NOT NULL,
  DESCRIPTION CHARACTER VARYING(255),
  MAIN_OFFICE_ADRESS_ID BIGINT,
  CONSTRAINT PK_COMPANY PRIMARY KEY (ID),
  CONSTRAINT UK_NAME UNIQUE (NAME),
  CONSTRAINT FK_ADDRESS FOREIGN KEY (MAIN_OFFICE_ADRESS_ID)
      REFERENCES ADDRESS (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);