CREATE TABLE DEPARTMENT
(
  ID BIGINT NOT NULL,
  NAME CHARACTER VARYING(255) NOT NULL,
  DESCRIPTION CHARACTER VARYING(255),
  COMPANY_ID BIGINT,
  CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID),
  CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_ID)
      REFERENCES COMPANY (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);