CREATE TABLE OFFICE
(
  ID BIGINT NOT NULL,
  ADDRESS_ID BIGINT,
  DEPARTMENT_ID BIGINT,
  NAME CHARACTER VARYING(255) NOT NULL,
  DESCRIPTION CHARACTER VARYING(255),
  CONSTRAINT PK_OFFICE PRIMARY KEY (ID),
  CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
      REFERENCES DEPARTMENT (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID)
      REFERENCES ADDRESS (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);