CREATE TABLE EMPLOYEE
(
  ID BIGINT NOT NULL,
  NAME CHARACTER VARYING(255) NOT NULL,
  SURNAME CHARACTER VARYING(255) NOT NULL,
  EMAIL CHARACTER VARYING(255),
  USER_ID INT8,
  ADDRESS_ID BIGINT,
  OFFICE_ID BIGINT,
  CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID),
  CONSTRAINT FK_OFFICE FOREIGN KEY (OFFICE_ID)
      REFERENCES OFFICE (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID)
      REFERENCES ADDRESS (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_USER FOREIGN KEY (USER_ID)
      REFERENCES USER_ (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);