CREATE TABLE WAREHOUSE
(
  ID BIGINT NOT NULL,
  NAME CHARACTER VARYING(255) NOT NULL,
  OFFICE_ID BIGINT,
  EMPLOYEE_ID BIGINT,
  CONSTRAINT PK_WAREHOUSE PRIMARY KEY (ID),
  CONSTRAINT FK_OFFICE FOREIGN KEY (OFFICE_ID)
      REFERENCES OFFICE (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
      REFERENCES EMPLOYEE (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);